### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by killbot24** [Bawnorton/DCFixes#1] opened 2024-07-10 22:16 UTC
DeceasedCraftFixes-1.0.5+1.18.2

[22:05:49] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
Negative index in crash report handler (16/18)
[22:05:49] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID d9c476e5-15af-45dc-b314-d14851080bdf
[22:05:49] [main/FATAL] [ne.mi.se.lo.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-07-10_22.05.49-fml.txt
[22:05:49] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 256b9a13-0c11-4cf6-8f24-f9370cea3869
[22:05:49] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        DeceasedCraft Fixes (dcfixes) has failed to load correctly
§7java.lang.ExceptionInInitializerError: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.4.jar%23236!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.4.jar%23236!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.4.jar%23236!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.4.jar%23236!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.4.jar%23236!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.4-universal.jar%23240!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23235!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.4.jar%2318!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by Bawnorton** [comment] 2024-07-10 22:52
I can't reproduce this

**Comment by killbot24** [comment] 2024-07-10 23:06
https://mclo.gs/QzcoWm2
Latest.log

I am still getting it on a fresh install

ah, it appears to be trying to do the button fixes on a dedi server,

**Comment by Bawnorton** [comment] 2024-07-10 23:47
That should only happen if a gui is loaded on the server.. I'll look into it tmrw

**Comment by Bawnorton** [comment] 2024-07-11 10:42
Fixed in 1.0.6

**Closed as completed by Bawnorton** 2024-07-11 10:42 UTC
